name: ETL pipeline
on:
    push:
        branches:
            - main
jobs:
    extract_jobs:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v2

            - name: run extract.py
              run: python extract.py


    transform_jobs:
        runs-on: ubuntu-latest
        needs: extract_jobs
        steps:
            - name: checkout code
              uses: actions/checkout@v2

            - name: run transform.py
              run: python transform.py


    load_jobs:
        runs-on: ubuntu-latest
        needs: transform_jobs
        steps:
            - name: checkout code
              uses: actions/checkout@v2

            - name: run load.py
              run: python load.py