name: ETL pipeline
on:
    push:
        branches:
            - main
jobs:
    install_pandas:
        runs-on: ubuntu-latest
        steps:
            - name: install pd
              run: pip install pandas


    extract_jobs:
        runs-on: ubuntu-latest
        needs: install_pandas
        steps:
            - name: checkout code
              uses: actions/checkout@v2

            - name: run extract.py
              run: python extract.py


    transform_jobs:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v2

            - name: run transform.py
              run: python transform.py


    load_jobs:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v2

            - name: run load.py
              run: python load.py